[functions.upload-avatar]
verify_jwt = false

[functions.get-activity-feed]
verify_jwt = false

[functions.upsert-profile]
verify_jwt = false

[functions.get-current-profile]
verify_jwt = false

[functions.get-nearby-players]
verify_jwt = false

[functions.create-direct-challenge]
verify_jwt = false

[functions.get-user-challenges]
verify_jwt = false
